# These are supported funding model platforms

github: [StephenHodgson,SimonDarksideJ,FejZa] # [XRTK, SimonDarksideJ, StephenHodgson]
ko_fi: xrtk_team
issuehunt: # simondarksidej
custom: http://paypal.me/XRTK
